# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'ExploreFlorida' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for ExploreFlorida
  react_native_path = "../node_modules/react-native"
  pod 'yoga', :path => "#{react_native_path}/ReactCommon/yoga"
  pod 'React', :path => react_native_path, :subspecs => [
    'RCTImage', # Required For React Native 0.45.0+
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
end
